import ButtonCreate from "./components/ButtonCreate";
import CreateModal from "./components/modals/CreateModal";
import Navbar from "./components/navbar/Navbar";
import SideMenu from "./components/navbar/SideMenu";
import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <CreateModal />
        <div className="flex">
          <SideMenu />
          <div className="flex-1 mx-auto py-4 h-screen overflow-y-scroll pt-20">
            <ButtonCreate />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
